name: Get list of recent papers
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.
        
      - name: set up recent.csv
        run: |
          echo "id" > _data/recent.csv
      - name: get recently updated files
        run: |
          git log --pretty=format: --name-only --since="7 days ago"  | grep -v -e '^$' | grep 'abs/' | head -n 10 | rev | cut -c 4- | rev >> _data/recent.csv
  
      - uses: stefanzweifel/git-auto-commit-action@v4
